# id администраторов
ADMIN_IDS: []

# Токен телеграм бота
TG_TOKEN: 123:abc

# токен платеги из BotFather (не используется)
PAYMENTS_TOKEN: 123

# coze api token
COZE_TOKEN: abc

# coze bot id
COZE_BOT_ID: 123

#deepgram api key
DG_API_KEY: abc

# цена подписки в рублях
PRICE: 500

# База данных aiosqlite
DB_FILE: db

# Часовой пояс
TIMEZONE: Europe/Moscow

# id канала для логов, бот админ в канале
LOGS_ID: -100123

# ссыль на канал/группу, бот должен быть админом в канале или участником в группе
CHANNEL_URL: https://t.me/abc

# id канала/группы
CHANNEL_ID: -100123

# лимиты базовой подписки
BASIC_LIMIT: 5

# лимиты платной подписки
PAID_LIMIT: 20

# адрес coze
COZE_URL: https://api.coze.com/open_api/v2/chat

        # # # # # # # # # # # # # #
        # payments robokassa data #
        # # # # # # # # # # # # # #

# тестовый ли платеж, нолик если нет, единица если да
IS_TEST: 1

ROBOKASSA_PAYMENT_URL: https://auth.robokassa.ru/Merchant/Index.aspx

# название магазина
MRH_LOGIN: abc

# пароль 1
PASS_1: abc

# пароль 2
PASS_2: abc

# тестовый пароль 1
TEST_PASS_1: dge

# тестовый пароль 2
TEST_PASS_2: efw

# описание
DESCRIPTION: Покупка месячной подписки на бота
